version: '3.8'

services:
  web:
    image: sudiptarathi2020/task-manager:latest
    ports:
      - "5000:5000"
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: taskmanager
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: